name: Check Documentation PR

on: 
  pull_request:
    branches:
      - main

jobs:
  check_pr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies with pip
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          pip install --no-warn-script-location --user --upgrade -r requirements.txt
          
      - name: Building documentation
        run: |
          make html