name: Check Documentation PR

on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        # with:
        #   python-version: 3.8

      - name: Install dependencies with pip
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          pip install --no-warn-script-location --user --upgrade -r requirements.txt
          
      - name: Building documentation
        run: |
          make html